### PR TITLE
warm-up period

### PR DESCRIPTION
**Pull request by notJoon**
WIP

xGNS -> lock-up period

### CODE REVIEW

**Comment by dongwon8247** [comment]
@notJoon Can you make it as a package instead as we discussed before with Blake? Then Blake can import this for the staker contract in GnoSwap.

**Comment by notJoon** [comment]
> @notJoon Can you make it as a package instead as we discussed before with Blake? Then Blake can import this for the staker contract in GnoSwap.

I'll make sure it works and then separate it into a package.

**Review by dongwon8247 — CHANGES_REQUESTED** [review]
As we discussed and chose to go with a simple lockup system with staking tokens, instead of the warm-up periods, blocking.

**Comment by r3v4s** [comment]
@notJoon I don't see any lock-up mechanism in current gov's staker, what's status of this pr?

**Pull request closed without merging**
